apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcarelog
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: petcarelog
          image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team5-petcarelog-prod:f26870754b17e1cb4f5dbfdee91cea34b8be295f