apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcarelog
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: petcarelog
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1024Mi"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petcarelog
spec:
  rules:
    - host: petcarelog.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petcarelog
                port:
                  number: 80
