apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcarelog
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: petcarelog
          image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team5-petcarelog-prod:d5aa2d7b2602ee2833516fca02845b9e56aa5a61