apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petcarelog-hpa
  namespace: petcarelog-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petcarelog
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30 # 시연용으로 30으로 낮게 잡음