apiVersion: v1
kind: Secret
metadata:
  name: petcarelog-secret
  namespace: petcarelog-dev
type: Opaque
stringData:
  DB_USERNAME: "petcarelog"
  DB_PASSWORD: "CHANGE_ME_DEV_DB_PASSWORD"

  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""