apiVersion: v1
kind: ServiceAccount
metadata:
  name: petcarelog-app-sa
  namespace: petcarelog-dev
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::194722398200:role/team5-petcarelog-dev-app-s3-irsa-role"