{
 "title": "쿠버네티스 / 인프라 상태",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "3. 배포 / 오토스케일링 상태",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HPA 현재 Replica 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{\r\n  namespace=\"petcarelog-prod\"\r\n}",
       "legendFormat": "현재 Replica"
      }
     ]
    },
    {
     "title": "HPA 목표 Replica 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{\r\n  namespace=\"petcarelog-prod\"\r\n}",
       "legendFormat": "목표 Replica"
      }
     ]
    },
    {
     "title": "HPA 스케일링 반응",
     "type": "timeseries",
     "description": "부하 발생 시 HPA가 목표 Replica를 올리고, 실제 Replica가 따라 올라가는지 확인",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{\r\n  namespace=\"petcarelog-prod\"\r\n}",
       "legendFormat": "현재 Replica"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{\r\n  namespace=\"petcarelog-prod\"\r\n}",
       "legendFormat": "목표 Replica"
      }
     ]
    },
    {
     "title": "HPA 최소 Replica 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{\r\n  namespace=\"petcarelog-prod\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HPA 최대 Replica 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{\r\n  namespace=\"petcarelog-prod\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deployment 설정  Replica 수",
     "type": "stat",
     "description": "Deployment에 설정된 Replica 수",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{\r\n  namespace=\"petcarelog-prod\",\r\n  deployment=~\"petcarelog.*\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "사용 가능한 Replica 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{\r\n  namespace=\"petcarelog-prod\",\r\n  deployment=~\"petcarelog.*\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "2. Pod 리소스 상태",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU 사용량",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"petcarelog-prod\",\r\n    pod=~\"petcarelog-.*\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }[5m])\r\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Memory 사용량",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"petcarelog-prod\",\r\n    pod=~\"petcarelog-.*\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }\r\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Ready 상태",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{\r\n  namespace=\"petcarelog-prod\",\r\n  condition=\"true\",\r\n  pod=~\"petcarelog-.*\"\r\n})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Phase 상태",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase) (\r\n  kube_pod_status_phase{\r\n    namespace=\"petcarelog-prod\",\r\n    pod=~\"petcarelog-.*\"\r\n  }\r\n)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Pod 재시작 횟수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\r\n  increase(kube_pod_container_status_restarts_total{\r\n    namespace=\"petcarelog-prod\",\r\n    pod=~\"petcarelog-.*\"\r\n  }[1h])\r\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "1. Node Ready 상태",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Ready 상태",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{\r\n  condition=\"Ready\",\r\n  status=\"true\"\r\n})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node CPU 사용률",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 -\r\n(\r\n  avg by (instance) (\r\n    rate(node_cpu_seconds_total{\r\n      mode=\"idle\"\r\n    }[5m])\r\n  ) * 100\r\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Memory 사용률",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\r\n  1 -\r\n  (\r\n    node_memory_MemAvailable_bytes\r\n    /\r\n    node_memory_MemTotal_bytes\r\n  )\r\n) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Disk 사용률",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\r\n  1 -\r\n  (\r\n    node_filesystem_avail_bytes{\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n    /\r\n    node_filesystem_size_bytes{\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n  )\r\n) * 100",
       "legendFormat": "{{instacne}} {{mountpoint}}"
      }
     ]
    }
   ]
  }
 ]
}